name: DbgPkg
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - altgraph=0.17.3
  - ansitable=0.10.0
  - attr=2.5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfgv=3.4.0
  - colored=1.4.4
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - dbus=1.13.18
  - distlib=0.3.8
  - double-conversion=3.3.0
  - expat=2.6.3
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.82.1
  - glib-tools=2.82.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - harfbuzz=9.0.0
  - icu=75.1
  - identify=2.5.5
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2022.0.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240722.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libclang=19.1.0
  - libclang-cpp15=15.0.7
  - libclang-cpp19.1=19.1.0
  - libclang13=19.1.0
  - libcups=2.3.3
  - libdeflate=1.21
  - libdrm=2.4.123
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.82.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libhwloc=2.9.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm19=19.1.1
  - libnsl=2.0.1
  - libntlm=1.6
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopengl=1.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=5.27.5
  - libsndfile=1.2.2
  - libsqlite=3.46.1
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=256.6
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.0
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.6
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=9.0.1
  - mysql-client=9.0.1
  - mysql-common=9.0.1
  - mysql-devel=9.0.1
  - mysql-libs=9.0.1
  - mysql-server=9.0.1
  - ncurses=6.4.20240210
  - networkx=3.3
  - nodeenv=1.7.0
  - nomkl=3.0
  - nspr=4.35
  - nss=3.105
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=3.10.0
  - ply=3.11
  - polars=1.9.0
  - pre-commit=3.4.0
  - pre_commit=3.4.0
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - pybind11-abi=5
  - pycparser=2.21
  - pyinstaller=6.10.0
  - pyinstaller-hooks-contrib=2024.7
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtgraph=0.13.7
  - pyside6=6.7.3
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - qhull=2020.2
  - qt-main=5.15.8
  - qt6-main=6.7.3
  - readline=8.2
  - scipy=1.13.1
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sortedcontainers=2.4.0
  - spatialmath-python=1.1.11
  - sphinxcontrib-jsmath=1.0.1
  - sqlite=3.31.1
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.13
  - tomli=2.0.2
  - tornado=6.4.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - virtualenv=20.26.1
  - wayland=1.23.1
  - wheel=0.44.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - iniconfig==2.0.0
      - pluggy==1.5.0
      - pytest==8.3.3
      - python-graphviz==0.20.3
