name: qt6_pip_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.55.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - numpy==2.0.2
      - packaging==24.2
      - pillow==11.0.0
      - pyparsing==3.2.0
      - pyside6==6.8.0.2
      - pyside6-addons==6.8.0.2
      - pyside6-essentials==6.8.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - shiboken6==6.8.0.2
      - six==1.16.0
      - zipp==3.21.0
      - pandas==2.2.2
      - networkx==3.3

